// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZTEmpo4m3G4ghJ4yYO97YWNdHBC6DFE',
    appId: '1:341548391342:web:10efa614b8df5e587b063f',
    messagingSenderId: '341548391342',
    projectId: 'moapp-project-59d01',
    authDomain: 'moapp-project-59d01.firebaseapp.com',
    storageBucket: 'moapp-project-59d01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgg-oGRR5-abtHrVSc01oj2PhQZw8Xm0',
    appId: '1:341548391342:android:aca272d551dc75757b063f',
    messagingSenderId: '341548391342',
    projectId: 'moapp-project-59d01',
    storageBucket: 'moapp-project-59d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdtmvFa0PyXv5JvhM3kYRlwRJpHEXr_sY',
    appId: '1:341548391342:ios:d9e3f0bf45e7fea87b063f',
    messagingSenderId: '341548391342',
    projectId: 'moapp-project-59d01',
    storageBucket: 'moapp-project-59d01.appspot.com',
    iosBundleId: 'com.example.moappProject',
  );
}
